export const START_FETCH_APEX_LOG = 'START_FETCH_APEX_LOG';
export const FETCH_APEX_LOG_SUCCEED = 'FETCH_APEX_LOG_SUCCEED';
export const FETCH_APEX_LOG_FAILED = 'FETCH_APEX_LOG_FAILED';
export const CLEAR_RESULT = 'CLEAR_RESULT';