export const START_EXECUTE_WEBSERVICE = 'START_EXECUTE_WEBSERVICE';
export const EXECUTE_WEBSERVICE_SUCCEED = 'EXECUTE_WEBSERVICE_SUCCEED';
export const EXECUTE_WEBSERVICE_FAILED = 'EXECUTE_WEBSERVICE_FAILED';
