export const SHOW_OBJECT_TYPE_COMBOBOX = 'SHOW_OBJECT_TYPE_COMBOBOX';
export const CHANGE_OBJECT_TYPE = 'CHANGE_OBJECT_TYPE';
export const SHOW_EXTERNAL_ID_FIELD_COMBOBOX =
    'SHOW_EXTERNAL_ID_FIELD_COMBOBOX';
export const CHANGE_EXTERNAL_ID_FIELD = 'CHANGE_EXTERNAL_ID_FIELD';
