export const SELECT_SOBJECT = 'SELECT_SOBJECT';
export const CLEAR_SELECTED_SOBJECT = 'CLEAR_SELECTED_SOBJECT';
export const SELECT_FIELD = 'SELECT_FIELD';
export const DESELECT_FIELD = 'DESELECT_FIELD';
export const CLEAR_SELECTED_FIELD = 'CLEAR_SELECTED_FIELD';
export const CREATE_JSON = 'CREATE_JSON';
export const CLEAR_JSON_STRING = 'CLEAR_JSON_STRING';
